### PR TITLE
rangeFloat

### PR DESCRIPTION
**Pull request by Fresheyeball**

### CODE REVIEW

**Comment by mgold** [comment]
What happens when a value gets shrunken outside the range? Actually that's a problem for `intRange` too. Not sure if clients would expect that or not.

Or, why would someone use the range function instead of checking all floats or ints?

All of that said, it makes sense to include this and have the shrinking strategy be consistent with `intRange`.

**Comment by Fresheyeball** [comment]
I needed it here: https://github.com/Fresheyeball/elm-yala/blob/master/Test/Main.elm
But `rangeFloat` fits better in `elm-check`, so I'm proposing.

**Comment by mgold** [comment]
I'll be adding this in the upcoming major release. Thanks for bringing this to my attention.

**Comment by Fresheyeball** [comment]
Thanks!

**Comment by mgold** [comment]
Oh and by the way, shruken values will be constrained to those in range. That's because, someone might set up the range knowing it's not valid outside the range. We don't want to shrink a legitimate error into an error they made a point of avoiding.

**Pull request closed without merging**
