### PR TITLE
Re-added the vanished Browser

### PR DESCRIPTION
**Pull request by newlandsvalley**
(compatible with Elm 0.16)

I don't know how you want to package the browser.  In this PR, you still compile Check.elm with the original dependencies.  I've also put in an example testbrowser directory which includes the extra dependency on elm-html so that the test compiles but I've left this dependency out of the main source.  It obviously need fixing somehow so you're happy with the dependencies.

### CODE REVIEW

**Comment by mgold** [comment]
I think this will be better handled by #2, namely, adding facilities to convert checks into tests and relying on elm-test to handle the runners. But I think we should keep the issue open until we have a definitive solution.

**Comment by newlandsvalley** [comment]
OK.  I have two questions about this approach:

Is there a straightforward installer for test-runner?  Will checks written using the DSL still work?

**Comment by mgold** [comment]
The runners are part of the `elm-test` package, which is just a normal Elm package, which exports `elementRunner`. You will also be able to run the tests through [this command line tool](https://www.npmjs.com/package/elm-test), but when it says it works with elm-check, well, it doesn't quite, yet. And from there, it will also work with CI builds.

Yes, you can use it with tests written in the DSL, since it's actually the `Evidence` that is converted into a test. I didn't spell that out in my first post, so this is a reasonable question.

The current elm-test integration (in `Check.Test`), which involves a separate DSL, is pretty worthless in my opinion, and I'd like to deprecate it once we get this better solution working.

**Comment by newlandsvalley** [comment]
OK - I'll be extremely happy if this all happens.  Many thanks.

**Comment by mgold** [comment]
200_s

3.0.0 should make it easy to get a browser view of the tests working. See the README for details.

**Comment by newlandsvalley** [comment]
Great improvement!  Many thanks, Max.,

**Pull request closed without merging**
